apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ft_service
spec:
  ports:
    - port: 21
      name: ftps-21
    - port: 20
      name: ftps-20
    - port: 10090
      name: ftps-ports90
    - port: 10091
      name: ftps-ports91
    - port: 10092
      name: ftps-ports92
    - port: 10093
      name: ftps-ports93
    - port: 10094
      name: ftps-ports94
    - port: 10095
      name: ftps-ports95
    - port: 10096
      name: ftps-ports96
    - port: 10097
      name: ftps-ports97
    - port: 10098
      name: ftps-ports98
    - port: 10099
      name: ftps-ports99
    - port: 10100
      name: ftps-ports100
  selector:
    app: ft_service
    tier: ftps
  type: LoadBalancer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ftps
  labels:
    app: ft_service
    tier: ftps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
    
---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ft_service
spec:
  selector:
    matchLabels:
      app: ft_service
      tier: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ft_service
        tier: ftps
    spec:
      containers:
      - image: my-ftps
        imagePullPolicy: Never
        name: ftps
        env:
        - name: FTPS_USER
          valueFrom:
            secretKeyRef:
              name: ftps
              key: user
        - name: FTPS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ftps
              key: password
        ports:
        - containerPort: 21
          hostPort: 21
        - containerPort: 20
          hostPort: 20
        - containerPort: 10090
          hostPort: 10090
        - containerPort: 10091
          hostPort: 10091
        - containerPort: 10092
          hostPort: 10092
        - containerPort: 10093
          hostPort: 10093
        - containerPort: 10094
          hostPort: 10094
        - containerPort: 10095
          hostPort: 10095
        - containerPort: 10096
          hostPort: 10096
        - containerPort: 10097
          hostPort: 10097
        - containerPort: 10098
          hostPort: 10098
        - containerPort: 10099
          hostPort: 10099
        - containerPort: 10100
          hostPort: 10100
        volumeMounts:
        - name: ftps-persistent-storage
          mountPath: /home
      volumes:
      - name: ftps-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-ftps
