apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: grafana-dashboards
  files:
    - images/grafana/dashboard.yaml
- name: grafana-datasources
  files:
    - images/grafana/datasource.yaml

secretGenerator:
- name: ftps
  literals:
  - user=noodles
  - password=spicy_noodles

- name: grafana
  literals:
  - http_port="3000"
  - auth_basic_enabled=false
  - auth_ano_enabled=true
  - auth_ano_org_role=Admin

- name: wordpress 
  literals:
  - db_host=mysql
  - db_user=root
  - db_password=root
  - db_name=wordpress

- name: mysql
  literals:
  - root_pass=root
  
resources:
- influxdb-config.yaml
- influxdb-secrets.yaml
- influxdb-deployment.yaml
- grafana-deployment.yaml
- nginx-deployment.yaml
- nginx-ingress.yaml
- ftps-deployment.yaml
- telegraf-config.yaml
- telegraf-secrets.yaml
- telegraf-deployment.yaml
- mysql-deployment.yaml
- wordpress-deployment.yaml
- phpmyadmin-deployment.yaml
