apiVersion: v1  
kind: Service  
metadata:  
  name: mysql
spec:  
  selector:  
    app: ft_service  
  ports:  
    - protocol: TCP  
      port: 3306 
  clusterIP: None

---

apiVersion: v1  
kind: PersistentVolumeClaim  
metadata:  
  name: mysql-pvc
spec:  
  accessModes:  
  - ReadWriteOnce  
  resources:  
    requests:  
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: ft_service
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: ft_service
    spec:
      containers:
      - image: my-mysql
        imagePullPolicy: Never
        name: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASS
          valueFrom:
            secretKeyRef:
              name: mysql
              key: root_pass
        volumeMounts:
        - name: mysql-pv
          mountPath: /app/mysql
      volumes:
      - name: mysql-pv
        persistentVolumeClaim:
          claimName: mysql-pvc
