apiVersion: v1  
kind: Service  
metadata:  
  name: wordpress
spec:  
  selector:  
    app: wordpress  
  ports:  
    - protocol: TCP  
      port: 5050 

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pvc
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
      
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: my-wordpress
          imagePullPolicy: Never
          name: wordpress
          ports:
            - containerPort: 5050
              hostPort: 5050
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
          env:
          - name: WORDPRESS_DB_HOST
            valueFrom:
              secretKeyRef:
                name: wordpress
                key: db_host
          - name: WORDPRESS_DB_USER 
            valueFrom:
              secretKeyRef:
                name: wordpress
                key: db_user
          - name: WORDPRESS_DB_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: wordpress
                key: db_password
          - name: WORDPRESS_DB_NAME 
            valueFrom:
              secretKeyRef:
                name: wordpress
                key: db_name
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pvc
